// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef mwidget_hxx
#define mwidget_hxx
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Button.H>
extern void onBnCalc(Fl_Button*, void*);
#include <FL/Fl_Output.H>
extern void onBnGen(Fl_Button*, void*);
extern void onBnHandle(Fl_Button*, void*);

class MWidget {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *mWindow;
  Fl_Spinner *spCLO;
  Fl_Spinner *spMET;
  Fl_Spinner *spWME;
  Fl_Spinner *spTA;
  Fl_Spinner *spVEL;
  Fl_Spinner *spTR;
  Fl_Spinner *spRH;
  Fl_Button *bnCalc;
  Fl_Output *spPMV;
  Fl_Output *spPPD;
  Fl_Output *spSET;
  Fl_Button *bnGen;
  Fl_Button *bnHandle;
};
#endif
